"""empty message

Revision ID: 20707de6979f
Revises: f64c4ab248ae
Create Date: 2024-11-23 11:01:11.739025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20707de6979f'
down_revision = 'f64c4ab248ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('total_statistics', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('total_statistics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
