"""Edit friend table

Revision ID: 32710a38b305
Revises: 206e08260fe3
Create Date: 2025-01-31 14:29:11.270410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32710a38b305'
down_revision = '206e08260fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('since', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('since')

    # ### end Alembic commands ###
